### ISSUE TITLE
org.h2.jdbc.JdbcSQLException: Table "USERCONNECTION" not found;

### ISSUE THREAD

**Issue by brunjick** [kevindeyne/simple-facebook-integration-spring-sec#2]
Is this expected behaviour for this demo?

```
org.h2.jdbc.JdbcSQLException: Table "USERCONNECTION" not found; SQL statement:
select userId, providerId, providerUserId, displayName, profileUrl, imageUrl, accessToken, secret, refreshToken, expireTime from UserConnection where userId = ? and providerId = ? order by rank [42102-194]
```

**Comment by kevindeyne** [comment]
No, but userconnection is not one of my files - I assume this is your domain object. 

According to the error, your table wasn't created yet. Note that in my application.properties I have the following:
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

Which should automatically create the tables required (but also drop them, if applicable!). Your project may vary - and for production usage I'd recommend using something like Flyway to actually build up your database (and something that doesn't drop stuff automatically).

Kind regards,

**Comment by brunjick** [comment]
@kevindeyne 
Thanks, I updated spring-social dependencies to latest versions since it wasn't compatible to current facebook api. I had to put this file as `schema.sql` in resources to fix

https://github.com/spring-projects/spring-social/blob/master/spring-social-core/src/main/resources/org/springframework/social/connect/jdbc/JdbcUsersConnectionRepository.sql
